### ISSUE TITLE
Надо добавить Яндекс.карту 

### ISSUE THREAD

**Issue by karapetyan** [13af/kartridzhi#2]
адрес:
Россия, Ставрополь, Морозова, 4

маркер поставить сюда:
http://prntscr.com/8z7zfz

**Comment by 13VF** [comment]
Нужна ли максимальная ширина в 1280px данному блоку?

**Comment by 13VF** [comment]
Пока добавил через конструктор карт (это сделано было за одну минуту). Позже добавлю используя яндекс.карты.api

**Comment by karapetyan** [comment]
ну как добавишь полноценную карту - пиши

**Comment by 13VF** [comment]
В процессе.

**Comment by 13VF** [comment]
Карта добавлена. Стандартные элементы управления адаптивны, это очень круто. Оставил полный набор стандартных элементов управления. Если ты считаешь что нужно добавить только определённые - говори что нужно.

**Comment by karapetyan** [comment]
http://prntscr.com/902y4z
http://prntscr.com/902ygm

**Comment by 13VF** [comment]
Исправил и переставил марку.
