### ISSUE TITLE
телефон в шапке и футере сделать активным

### ISSUE THREAD

**Issue by karapetyan** [13af/kartridzhi#3]
http://stackoverflow.com/questions/4572297/is-there-a-way-to-make-a-phone-number-clickable-on-an-iphone-or-android-phone-to

**Comment by 13VF** [comment]
Телефон сделан ссылкой href="tel:"

**Comment by karapetyan** [comment]
не сделано. При просмотре сайта с iphone и нажатии на номер телефона в шапке мне ios не предлагает "позвонить" по этому номеру. А следовательно что-то сделано не так

**Comment by 13VF** [comment]
Проверил в браузерах на андроиде и iOS, и на десктопе: chrome, safari. Работает. Попробуй ещё раз, пожалуйста.

**Comment by karapetyan** [comment]
подтверждаю, все ок
