### ISSUE TITLE
При потере фокуса поле с номером телефона и именем не должно стирать введенное значение

### ISSUE THREAD

**Issue by karapetyan** [13af/kartridzhi#4]
https://plugins.jquery.com/intl-tel-input/

пример как должно быть:
http://mrt-sana.com

**Comment by 13VF** [comment]
Подключил masked input.

**Comment by karapetyan** [comment]
http://prntscr.com/8zm6tn

**Comment by 13VF** [comment]
Моя ошибка - забыл про три цифры. Исправлено.

**Comment by karapetyan** [comment]
При вводе неполного номера, например,
90341998 
нажатии сабмит, возникает ошибка валидации, но проблема в том, что данные удаляются и я вынужден вводить их повторно. 

В случае если сабмит не был успешен и данные не прошли валидацию, они не должны удаляться в любом случае.

**Comment by karapetyan** [comment]
А то вводить номер телефона как-то лень с нуля

**Comment by karapetyan** [comment]
проблема актуальна

**Comment by 13VF** [comment]
Изменил маскдинпут на инпутмаск :)

**Comment by karapetyan** [comment]
ок
