### ISSUE TITLE
Адаптивность

### ISSUE THREAD

**Issue by karapetyan** [13af/kartridzhi#6]
http://prntscr.com/8z83cs

**Comment by 13VF** [comment]
Сделал с исчезновением картинки совсем. Требует оценки.

**Comment by karapetyan** [comment]
Сейчас в мобильном вью сильно увеличиваются размеры шрифта, кнопок и прочего. Хотелось бы, что б все разрмеры шрифтов и кнопки оставались как в планшетной версии, а менялась только _шапка_ и футер, ге фактически не помещаются адрес и телефон. Хедер и футер сейчас меняются как надо. И это единственное, что должно меняться в мобильной версии по отношению к планшетной.

Раз уж ты сделал удаление картинки - фиг с ним, пусть будет без картинки в мобильном

**Comment by karapetyan** [comment]
А то сейчас мобильная версия == версия для слабовидящих

**Comment by 13VF** [comment]
Отписал в ВК относительно адаптивных изменений. Убрал увеличение шрифта для большинства элементов. Оставил только форму, футер, со стилями из изначального макета. Если что - убрать можно быстро.

**Comment by karapetyan** [comment]
http://prntscr.com/8zrn8k

**Comment by karapetyan** [comment]
в остальном ок

**Comment by 13VF** [comment]
Убрал увеличение и для формы.

**Comment by karapetyan** [comment]
ок
