### ISSUE TITLE
Не работает валидация

### ISSUE THREAD

**Issue by karapetyan** [13af/kartridzhi#8]
при попытке нажать на кнопку "отправить" с незаполненными полями формы, ничего не происходит. Алертов о том, что поля не заполнены - не получаю.

**Comment by 13VF** [comment]
Сделал сабмит на кнопку, а также на нажатие кнопки энтер. Также, делаю проверку при сабмите на наличие ошибок в инпутах.

Меняется цвет рамки инпутов при ошибке в инпуте.

**Comment by karapetyan** [comment]
валидация все еще не работает. В имя входят следующие диапазоны: а-яА-Яa-zA-Z
и пробелы разрешены

**Comment by karapetyan** [comment]
а сейчас и цифры, и спецсимволы прокатывают

**Comment by 13VF** [comment]
Прикрутил регулярку. Должно работать как надо.

**Comment by karapetyan** [comment]
работает
